services:
  adsb-module:
    image: ghcr.io/jaggornaut/adsb-module:latest
    build: .
    network_mode: host
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./config:/config:ro
    restart: unless-stopped
